"""
Key Derivation Functions.

Provides HKDF-SHA256 for session key derivation and Short Authentication
String (SAS) generation for out-of-band MitM verification.
"""

from __future__ import annotations

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

_SESSION_KEY_SIZE = 32  # 256-bit AES key
_SAS_BYTES = 3  # 3 bytes → 6 hex chars


def derive_session_key(
    k_classical: bytes,
    k_pq: bytes,
    salt: bytes,
    info: bytes = b"hermod-session-v1",
) -> bytes:
    """Derive a 256-bit session key from classical and PQ shared secrets.

    Parameters
    ----------
    k_classical:
        Shared secret produced by SPAKE2 PAKE.
    k_pq:
        Shared secret produced by ML-KEM (or X25519 fallback).
    salt:
        A fresh random salt generated by the sender.
    info:
        HKDF context / application label.

    Returns
    -------
    bytes
        32-byte composite session key.
    """
    if not k_classical:
        raise ValueError("k_classical must be non-empty")
    if not k_pq:
        raise ValueError("k_pq must be non-empty")
    if not salt:
        raise ValueError("salt must be non-empty")

    combined = k_classical + k_pq
    return HKDF(
        algorithm=hashes.SHA256(),
        length=_SESSION_KEY_SIZE,
        salt=salt,
        info=info,
    ).derive(combined)


def derive_sas(session_key: bytes) -> str:
    """Derive a 6-character hex Short Authentication String.

    Used for out-of-band verification (MitM protection). Both peers derive
    the same SAS from the agreed ``session_key`` and compare verbally.

    Parameters
    ----------
    session_key:
        The 32-byte composite session key.

    Returns
    -------
    str
        6-character uppercase hex string (e.g. ``"A3F7C1"``).
    """
    if len(session_key) != 32:
        raise ValueError(f"session_key must be 32 bytes; got {len(session_key)}")
    sas_bytes = HKDF(
        algorithm=hashes.SHA256(),
        length=_SAS_BYTES,
        salt=None,
        info=b"hermod-sas-v1",
    ).derive(session_key)
    return sas_bytes.hex().upper()
