"""
Key Derivation Functions.

Provides HKDF-SHA256 for session key derivation and Short Authentication
String (SAS) generation for out-of-band MitM verification.

Session key construction (v2):

    IKM = k_classical ‖ k_ecdh ‖ k_pq

Three independent secrets must all be secure for the session key to be
secure:

* ``k_classical`` — SPAKE2 PAKE (classical, authentication layer)
* ``k_ecdh``      — ephemeral X25519 DH (classical, defence-in-depth against
                    PQ being broken by a classical computer)
* ``k_pq``        — ML-KEM-768 (post-quantum, defence against harvest-now
                    decrypt-later attacks)
"""

from __future__ import annotations

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

_SESSION_KEY_SIZE = 32  # 256-bit AES key
_SAS_BYTES = 3  # 3 bytes → 6 hex chars


def derive_session_key(
    k_classical: bytes,
    k_ecdh: bytes,
    k_pq: bytes,
    salt: bytes,
    info: bytes = b"hermod-session-v2",
) -> bytes:
    """Derive a 256-bit session key from three independent shared secrets.

    Parameters
    ----------
    k_classical:
        Shared secret produced by SPAKE2 PAKE.
    k_ecdh:
        Shared secret produced by ephemeral X25519 DH.
    k_pq:
        Shared secret produced by ML-KEM-768 (or X25519 fallback).
    salt:
        A fresh random salt generated by the sender.
    info:
        HKDF context / application label.

    Returns
    -------
    bytes
        32-byte composite session key.
    """
    if not k_classical:
        raise ValueError("k_classical must be non-empty")
    if not k_ecdh:
        raise ValueError("k_ecdh must be non-empty")
    if not k_pq:
        raise ValueError("k_pq must be non-empty")
    if not salt:
        raise ValueError("salt must be non-empty")

    combined = k_classical + k_ecdh + k_pq
    return HKDF(
        algorithm=hashes.SHA256(),
        length=_SESSION_KEY_SIZE,
        salt=salt,
        info=info,
    ).derive(combined)


def derive_resume_key(session_key: bytes, resume_counter: int) -> bytes:
    """Derive a unique sub-key for a resumed transfer segment.

    Appendix B §2 mandates that the original ``session_key`` is NEVER reused
    for a resumed transfer.  Each resumption must produce a fresh key bound to
    a monotonically increasing counter.

    Parameters
    ----------
    session_key:
        The 32-byte composite session key from the initial exchange.
    resume_counter:
        A strictly increasing integer identifying this resume segment
        (e.g. the number of previous resume attempts).

    Returns
    -------
    bytes
        32-byte sub-key unique to this resumption segment.
    """
    if len(session_key) != _SESSION_KEY_SIZE:
        raise ValueError(
            f"session_key must be {_SESSION_KEY_SIZE} bytes; got {len(session_key)}"
        )
    if resume_counter < 0:
        raise ValueError("resume_counter must be non-negative")
    return HKDF(
        algorithm=hashes.SHA256(),
        length=_SESSION_KEY_SIZE,
        salt=None,
        info=b"hermod-resume-v1:" + resume_counter.to_bytes(8, "big"),
    ).derive(session_key)


def derive_sas(session_key: bytes) -> str:
    """Derive a 6-character hex Short Authentication String.

    Used for out-of-band verification (MitM protection). Both peers derive
    the same SAS from the agreed ``session_key`` and compare verbally.

    Parameters
    ----------
    session_key:
        The 32-byte composite session key.

    Returns
    -------
    str
        6-character uppercase hex string (e.g. ``"A3F7C1"``).
    """
    if len(session_key) != 32:
        raise ValueError(f"session_key must be 32 bytes; got {len(session_key)}")
    sas_bytes = HKDF(
        algorithm=hashes.SHA256(),
        length=_SAS_BYTES,
        salt=None,
        info=b"hermod-sas-v1",
    ).derive(session_key)
    return sas_bytes.hex().upper()
