// Code generated by scripts/bump-version.sh; DO NOT EDIT.
package cli

// appVersion is the current application version.
// Updated automatically by scripts/bump-version.sh.
const appVersion = "1.0.0"
